services:
  - type: web
    name: yalla-foot
    env: node
    nodeVersion: 18.x
    buildCommand: |
      npm ci
      npx react-scripts build
    startCommand: |
      npm install -g serve
      serve -s build -l $PORT
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
